#!/usr/bin/env python3
"""
Demo script for markdown processing in PageIndex.
Shows how to process markdown files generated by marker or similar tools.
"""

import json
import sys
from pathlib import Path

from pageindex.markdown_integration import (
    markdown_page_index,
    enhance_pdf_structure_with_markdown,
    create_hybrid_structure
)
from pageindex.utils import print_toc


def demo_basic_markdown_processing():
    """Demo: Basic markdown to PageIndex structure."""
    print("\n" + "="*60)
    print("DEMO 1: Basic Markdown Processing")
    print("="*60)
    
    markdown_path = "PageIndex/tests/markdowns/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries.md"
    metadata_path = "PageIndex/tests/markdowns/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries_meta.json"
    
    if not Path(markdown_path).exists():
        print(f"Markdown file not found: {markdown_path}")
        return
    
    # Process markdown
    structure = markdown_page_index(
        markdown_path=markdown_path,
        metadata_path=metadata_path,
        opt={'if_add_node_text': 'no', 'if_add_node_summary': 'no'}
    )
    
    print(f"\nDocument Structure:")
    print(f"  Total pages: {structure['page_count']}")
    print(f"  Top-level sections: {len(structure['tree'])}")
    print(f"  Figures found: {len(structure.get('figures', []))}")
    print(f"  Tables found: {len(structure.get('tables', []))}")
    
    print("\nTable of Contents:")
    print_toc(structure['tree'])
    
    # Save structure
    output_path = "PageIndex/results/markdown_structure_demo.json"
    Path("results").mkdir(exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(structure, f, indent=2)
    print(f"\nStructure saved to: {output_path}")


def demo_markdown_with_text():
    """Demo: Extract text content from markdown."""
    print("\n" + "="*60)
    print("DEMO 2: Markdown Processing with Text Extraction")
    print("="*60)
    
    markdown_path = "PageIndex/tests/markdowns/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries.md"
    metadata_path = "PageIndex/tests/markdowns/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries_meta.json"
    
    if not Path(markdown_path).exists():
        print(f"Markdown file not found: {markdown_path}")
        return
    
    # Process with text extraction
    structure = markdown_page_index(
        markdown_path=markdown_path,
        metadata_path=metadata_path,
        opt={'if_add_node_text': 'yes', 'if_add_node_summary': 'no'}
    )
    
    # Show first section with text
    if structure['tree']:
        first_section = structure['tree'][0]
        print(f"\nFirst section: {first_section['title']}")
        print(f"  Pages: {first_section.get('start_page', 'N/A')} - {first_section.get('end_page', 'N/A')}")
        if 'text' in first_section:
            text_preview = first_section['text'][:200] + "..." if len(first_section['text']) > 200 else first_section['text']
            print(f"  Text preview: {text_preview}")
            print(f"  Token count: {first_section.get('token_count', 'N/A')}")


def demo_figure_extraction():
    """Demo: Extract figures from markdown."""
    print("\n" + "="*60)
    print("DEMO 3: Figure and Table Extraction")
    print("="*60)
    
    markdown_path = "PageIndex/tests/markdowns/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries.md"
    metadata_path = "PageIndex/tests/markdowns/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries/Influence of the LLZO-PEO interface on the micro- and macro-scale properties of composite polymer electrolytes for solid-state batteries_meta.json"
    
    if not Path(markdown_path).exists():
        print(f"Markdown file not found: {markdown_path}")
        return
    
    structure = markdown_page_index(
        markdown_path=markdown_path,
        metadata_path=metadata_path
    )
    
    # Show figures
    figures = structure.get('figures', [])
    print(f"\nFound {len(figures)} figures:")
    for fig in figures[:5]:  # Show first 5
        print(f"  - Figure {fig['figure_number']} on page {fig['page']}")
    
    # Show tables
    tables = structure.get('tables', [])
    print(f"\nFound {len(tables)} tables:")
    for i, table in enumerate(tables[:3], 1):
        print(f"  - Table {i}: lines {table['line_start']}-{table['line_end']}")


def demo_comparison():
    """Demo: Compare markdown vs PDF extraction quality."""
    print("\n" + "="*60)
    print("DEMO 4: Markdown vs PDF Comparison")
    print("="*60)
    
    print("\nMarkdown advantages:")
    print("  ✓ Better text extraction (preserves formatting)")
    print("  ✓ Extracted figures as separate image files")
    print("  ✓ Cleaner table detection")
    print("  ✓ Preserved subscripts/superscripts")
    print("  ✓ Better handling of multi-column layouts")
    print("  ✓ Metadata includes document structure")
    
    print("\nPDF advantages:")
    print("  ✓ Direct access to original document")
    print("  ✓ Precise bounding boxes for elements")
    print("  ✓ No preprocessing required")
    
    print("\nRecommendation:")
    print("  Use markdown when available for better text quality")
    print("  Use hybrid approach for best of both worlds")


def main():
    """Run all demos."""
    print("\n" + "="*60)
    print("PageIndex Markdown Processing Demo")
    print("="*60)
    
    demos = [
        ("Basic Processing", demo_basic_markdown_processing),
        ("Text Extraction", demo_markdown_with_text),
        ("Figure Extraction", demo_figure_extraction),
        ("Comparison", demo_comparison)
    ]
    
    if len(sys.argv) > 1:
        # Run specific demo
        demo_num = int(sys.argv[1])
        if 1 <= demo_num <= len(demos):
            name, func = demos[demo_num - 1]
            print(f"\nRunning: {name}")
            func()
        else:
            print(f"Invalid demo number. Choose 1-{len(demos)}")
    else:
        # Run all demos
        for name, func in demos:
            try:
                func()
            except Exception as e:
                print(f"\nError in {name}: {e}")
                import traceback
                traceback.print_exc()
    
    print("\n" + "="*60)
    print("Demo complete!")
    print("="*60)


if __name__ == "__main__":
    main()
